title: System Conference Deadlines # (Maintained by @l34p)
# email: hmg0228@unist.ac.kr
description: Countdowns to top system conference deadlines
author: Myeonggyun Han

domain: "l34p.github.io"
baseurl: ""

github_username: l34p
github_repo: sys-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
